// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: tag.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TagClient is the client API for Tag service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TagClient interface {
	CreateTag(ctx context.Context, in *TagName, opts ...grpc.CallOption) (*TagId, error)
	GetTagByName(ctx context.Context, in *TagName, opts ...grpc.CallOption) (*TagData, error)
	AddTweet(ctx context.Context, in *AddTweetParams, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteTweet(ctx context.Context, in *TweetIdParam, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetTagById(ctx context.Context, in *TagId, opts ...grpc.CallOption) (*TagData, error)
}

type tagClient struct {
	cc grpc.ClientConnInterface
}

func NewTagClient(cc grpc.ClientConnInterface) TagClient {
	return &tagClient{cc}
}

func (c *tagClient) CreateTag(ctx context.Context, in *TagName, opts ...grpc.CallOption) (*TagId, error) {
	out := new(TagId)
	err := c.cc.Invoke(ctx, "/tag.Tag/CreateTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) GetTagByName(ctx context.Context, in *TagName, opts ...grpc.CallOption) (*TagData, error) {
	out := new(TagData)
	err := c.cc.Invoke(ctx, "/tag.Tag/GetTagByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) AddTweet(ctx context.Context, in *AddTweetParams, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tag.Tag/AddTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) DeleteTweet(ctx context.Context, in *TweetIdParam, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/tag.Tag/DeleteTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) GetTagById(ctx context.Context, in *TagId, opts ...grpc.CallOption) (*TagData, error) {
	out := new(TagData)
	err := c.cc.Invoke(ctx, "/tag.Tag/GetTagById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagServer is the server API for Tag service.
// All implementations must embed UnimplementedTagServer
// for forward compatibility
type TagServer interface {
	CreateTag(context.Context, *TagName) (*TagId, error)
	GetTagByName(context.Context, *TagName) (*TagData, error)
	AddTweet(context.Context, *AddTweetParams) (*emptypb.Empty, error)
	DeleteTweet(context.Context, *TweetIdParam) (*emptypb.Empty, error)
	GetTagById(context.Context, *TagId) (*TagData, error)
	mustEmbedUnimplementedTagServer()
}

// UnimplementedTagServer must be embedded to have forward compatible implementations.
type UnimplementedTagServer struct {
}

func (UnimplementedTagServer) CreateTag(context.Context, *TagName) (*TagId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedTagServer) GetTagByName(context.Context, *TagName) (*TagData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTagByName not implemented")
}
func (UnimplementedTagServer) AddTweet(context.Context, *AddTweetParams) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTweet not implemented")
}
func (UnimplementedTagServer) DeleteTweet(context.Context, *TweetIdParam) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTweet not implemented")
}
func (UnimplementedTagServer) GetTagById(context.Context, *TagId) (*TagData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTagById not implemented")
}
func (UnimplementedTagServer) mustEmbedUnimplementedTagServer() {}

// UnsafeTagServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TagServer will
// result in compilation errors.
type UnsafeTagServer interface {
	mustEmbedUnimplementedTagServer()
}

func RegisterTagServer(s grpc.ServiceRegistrar, srv TagServer) {
	s.RegisterService(&Tag_ServiceDesc, srv)
}

func _Tag_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tag.Tag/CreateTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).CreateTag(ctx, req.(*TagName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_GetTagByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).GetTagByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tag.Tag/GetTagByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).GetTagByName(ctx, req.(*TagName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_AddTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTweetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).AddTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tag.Tag/AddTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).AddTweet(ctx, req.(*AddTweetParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_DeleteTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TweetIdParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).DeleteTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tag.Tag/DeleteTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).DeleteTweet(ctx, req.(*TweetIdParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_GetTagById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).GetTagById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tag.Tag/GetTagById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).GetTagById(ctx, req.(*TagId))
	}
	return interceptor(ctx, in, info, handler)
}

// Tag_ServiceDesc is the grpc.ServiceDesc for Tag service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tag_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tag.Tag",
	HandlerType: (*TagServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTag",
			Handler:    _Tag_CreateTag_Handler,
		},
		{
			MethodName: "GetTagByName",
			Handler:    _Tag_GetTagByName_Handler,
		},
		{
			MethodName: "AddTweet",
			Handler:    _Tag_AddTweet_Handler,
		},
		{
			MethodName: "DeleteTweet",
			Handler:    _Tag_DeleteTweet_Handler,
		},
		{
			MethodName: "GetTagById",
			Handler:    _Tag_GetTagById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tag.proto",
}
