apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (HEAD)
  labels:
    io.kompose.service: twitter-clone-tag
  name: twitter-clone-tag
spec:
  ports:
  - name: "7007"
    port: 7007
    targetPort: 7007
  selector:
    io.kompose.service: twitter-clone-tag
status:
  loadBalancer: {}