port: "7006"

db:
  host: "db-tweet"
  port: "5436"
  username: "postgres"
  dbname: "postgres"
  password: "postgreSQL"
  sslmode: "disable"

services:
  message: "twitter-clone-message:7004"
  tag: "twitter-clone-tag:7007"
  user: "twitter-clone-user:7003"