version: "3"

services:
  twitter-clone-user:
    build: 
      context: ../../
      dockerfile: services/user/Dockerfile
    command: services/user/wait-for-postgres.sh db services/user/twitter-clone-user
    ports:
      - 7003:7003
    depends_on:
      - db
    networks:
      - twitter-clone
      - user-internal
  
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgreSQL
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    networks:
      - user-internal

volumes:
  db:
    driver: local

networks: 
  twitter-clone:
    name: twitter-clone
    external: true
  user-internal:
    name: user-internal