port: "7005"

db:
  host: "db"
  port: "5432"
  username: "postgres"
  dbname: "postgres"
  password: "postgreSQL"
  sslmode: "disable"

services:
  message: "twitter-clone-message:7004"
  tweet: "twitter-clone-tweet:7006"