apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (HEAD)
  labels:
    io.kompose.service: twitter-clone-redis
  name: twitter-clone-redis
spec:
  ports:
  - name: "7002"
    port: 7002
    targetPort: 7002
  selector:
    io.kompose.service: twitter-clone-redis
status:
  loadBalancer: {}
