version: "3.8"

services:
  twitter-clone-redis:
    build: ./
    command: ./twitter-clone-redis
    ports:
      - 7002:7002
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:latest
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
    ports:
      - 6379:6379

volumes:
  redis:
    driver: local